# typed: false
# frozen_string_literal: true

# This file is auto-generated by GoReleaser. Do not edit manually.
# To update, create a new release in the alicloud-nuke repository.

class AliNuke < Formula
  desc "A command-line tool to delete all resources from an Alibaba Cloud account"
  homepage "https://github.com/arafato/alicloud-nuke"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/arafato/alicloud-nuke/releases/download/v0.5.0/ali-nuke_0.5.0_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_AMD64"
    end
    on_arm do
      url "https://github.com/arafato/alicloud-nuke/releases/download/v0.5.0/ali-nuke_0.5.0_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arafato/alicloud-nuke/releases/download/v0.5.0/ali-nuke_0.5.0_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"
    end
    on_arm do
      url "https://github.com/arafato/alicloud-nuke/releases/download/v0.5.0/ali-nuke_0.5.0_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
    end
  end

  def install
    bin.install "ali-nuke"
  end

  test do
    system "#{bin}/ali-nuke", "version"
  end
end
