# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AliNuke < Formula
  desc "A command-line tool to delete all resources from an Alibaba Cloud account"
  homepage "https://github.com/arafato/alicloud-nuke"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafato/alicloud-nuke/releases/download/v0.5.1/ali-nuke_0.5.1_darwin_amd64.tar.gz"
      sha256 "46197cd53aafd9946b56693e694422d826e3caa496eb0287bbf7a4015e193601"

      def install
        bin.install "ali-nuke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafato/alicloud-nuke/releases/download/v0.5.1/ali-nuke_0.5.1_darwin_arm64.tar.gz"
      sha256 "8861f803509155283cbcd9f9aa18fbbf597380630d9848907c614f64a297af01"

      def install
        bin.install "ali-nuke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/alicloud-nuke/releases/download/v0.5.1/ali-nuke_0.5.1_linux_amd64.tar.gz"
      sha256 "a3ed238df18c73ebd721d5cbcfe1e62cf8e6e4c6367bfd58da6a38dc7d1efe8c"
      def install
        bin.install "ali-nuke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/alicloud-nuke/releases/download/v0.5.1/ali-nuke_0.5.1_linux_arm64.tar.gz"
      sha256 "0d311128ef59880e042c069dbf9ce8d3042d4c675494389a6cd076c2c3bb50e2"
      def install
        bin.install "ali-nuke"
      end
    end
  end

  test do
    system "#{bin}/ali-nuke", "version"
  end
end
