# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfNuke < Formula
  desc "A command-line tool to delete all resources from a Cloudflare account"
  homepage "https://github.com/arafato/cf-nuke"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.8.2/cf-nuke_0.8.2_darwin_amd64.tar.gz"
      sha256 "87accf550f88915b164d89b9562e4195e6ced6dcf753730baf3e60eb6a2d3d14"

      def install
        bin.install "cf-nuke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.8.2/cf-nuke_0.8.2_darwin_arm64.tar.gz"
      sha256 "5a3a20685397137c1e6800cee4f6e83686a3bec8f558f52cb81711a5b21e6ff6"

      def install
        bin.install "cf-nuke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.8.2/cf-nuke_0.8.2_linux_amd64.tar.gz"
      sha256 "7ad96ef5417fadada89977b36c9a5377b636426c1a7339bf9786b29a0cb1b4de"
      def install
        bin.install "cf-nuke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.8.2/cf-nuke_0.8.2_linux_arm64.tar.gz"
      sha256 "e32d099bae7d0c53221f52c8900b76bc2a6c6f58e7080eb018e10422feb86e8a"
      def install
        bin.install "cf-nuke"
      end
    end
  end

  test do
    system "#{bin}/cf-nuke", "version"
  end
end
