# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfNuke < Formula
  desc "A command-line tool to delete all resources from a Cloudflare account"
  homepage "https://github.com/arafato/cf-nuke"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.9.0/cf-nuke_0.9.0_darwin_amd64.tar.gz"
      sha256 "0a9f4f3a51b585bdd0f69bf3f4f3f27e26ee937148a4f045d30b69a44ad4d255"

      define_method(:install) do
        bin.install "cf-nuke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.9.0/cf-nuke_0.9.0_darwin_arm64.tar.gz"
      sha256 "0072794705a47aec0e1afc8ee8c1f2706fc1095d581a21ca173ef06ef14a5d80"

      define_method(:install) do
        bin.install "cf-nuke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.9.0/cf-nuke_0.9.0_linux_amd64.tar.gz"
      sha256 "5087a6b176fe2c4a2302655bb713f826e54852e106452636098c67585984ad00"
      define_method(:install) do
        bin.install "cf-nuke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.9.0/cf-nuke_0.9.0_linux_arm64.tar.gz"
      sha256 "f3946d368fcb449256ceae9b73e4d5c178967cc8876907e44d26632d0dbd32bf"
      define_method(:install) do
        bin.install "cf-nuke"
      end
    end
  end

  test do
    system "#{bin}/cf-nuke", "version"
  end
end
