# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfNuke < Formula
  desc "A command-line tool to delete all resources from a Cloudflare account"
  homepage "https://github.com/arafato/cf-nuke"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.8.1/cf-nuke_0.8.1_darwin_amd64.tar.gz"
      sha256 "de1a772f48eedf0cd316d2c2c55d2875a2f81cbc0244cd3d8760a42e08e25878"

      def install
        bin.install "cf-nuke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.8.1/cf-nuke_0.8.1_darwin_arm64.tar.gz"
      sha256 "5f9174530db2c1def4bab97d2b2599d130df9b8cc1965b9134085102e01e84f3"

      def install
        bin.install "cf-nuke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.8.1/cf-nuke_0.8.1_linux_amd64.tar.gz"
      sha256 "8732558aaf0cc97b912a973d94bbb11559e21785d6cc6091e73c4afabb350af2"
      def install
        bin.install "cf-nuke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/cf-nuke/releases/download/v0.8.1/cf-nuke_0.8.1_linux_arm64.tar.gz"
      sha256 "5ff06edb4deda76266e348125a21995299508234aeedd0de879196d39b2153bd"
      def install
        bin.install "cf-nuke"
      end
    end
  end

  test do
    system "#{bin}/cf-nuke", "version"
  end
end
