# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orangeshell < Formula
  desc "A TUI dashboard for managing the Cloudflare Developer Platform"
  homepage "https://github.com/arafato/orangeshell"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafato/orangeshell/releases/download/v1.2.0/orangeshell_1.2.0_darwin_amd64.tar.gz"
      sha256 "27caa18a3f47c5cf2c1a6913d80e4b2686e28bbd6a2a71ba6958a7b3498a5ad1"

      def install
        bin.install "orangeshell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafato/orangeshell/releases/download/v1.2.0/orangeshell_1.2.0_darwin_arm64.tar.gz"
      sha256 "974467887e1380adb00abb40925ba9ffaf508ed8439dd0950fadefb491b213b8"

      def install
        bin.install "orangeshell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/orangeshell/releases/download/v1.2.0/orangeshell_1.2.0_linux_amd64.tar.gz"
      sha256 "699585192c05a821d75d2d83ab4065f4ccff47b04e15ee87ed5a46db317b7aa4"
      def install
        bin.install "orangeshell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/orangeshell/releases/download/v1.2.0/orangeshell_1.2.0_linux_arm64.tar.gz"
      sha256 "7bf2c9a6a89919b6c2d31f537e8e2cea43f8a04eeba19bb9ab16b636891beb65"
      def install
        bin.install "orangeshell"
      end
    end
  end

  test do
    system "#{bin}/orangeshell", "--version"
  end
end
