# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orangeshell < Formula
  desc "A TUI dashboard for managing the Cloudflare Developer Platform"
  homepage "https://github.com/arafato/orangeshell"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafato/orangeshell/releases/download/v0.5.0/orangeshell_0.5.0_darwin_amd64.tar.gz"
      sha256 "d0858219d3104afa0c91e97beb7a3c1911e1e3802f1f3c45064b2f4a891fbaab"

      def install
        bin.install "orangeshell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafato/orangeshell/releases/download/v0.5.0/orangeshell_0.5.0_darwin_arm64.tar.gz"
      sha256 "fcb3576d8debe9d38004badfec12e9cc7f738b477a451c9410240c0f1962736f"

      def install
        bin.install "orangeshell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/orangeshell/releases/download/v0.5.0/orangeshell_0.5.0_linux_amd64.tar.gz"
      sha256 "60c96acab77d3831b77f91b87d5017374a0919fc248529f6d2906211c24f9642"
      def install
        bin.install "orangeshell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/orangeshell/releases/download/v0.5.0/orangeshell_0.5.0_linux_arm64.tar.gz"
      sha256 "a2ed5793fe3edd02f22eb00e46ed85219875b7caaf10e2ef429c3c4afe2a52e7"
      def install
        bin.install "orangeshell"
      end
    end
  end

  test do
    system "#{bin}/orangeshell", "--version"
  end
end
