# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orangeshell < Formula
  desc "A TUI dashboard for managing the Cloudflare Developer Platform"
  homepage "https://github.com/arafato/orangeshell"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arafato/orangeshell/releases/download/v1.7.0/orangeshell_1.7.0_darwin_amd64.tar.gz"
      sha256 "11bc740398474c4356dadf1e0a96d359244ebe45998be15b8405625aa57ec015"

      define_method(:install) do
        bin.install "orangeshell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arafato/orangeshell/releases/download/v1.7.0/orangeshell_1.7.0_darwin_arm64.tar.gz"
      sha256 "b8d61b6e54cee5c8729ab725566e8c71fa1706bc7778a8a36422b0bb2ce5adae"

      define_method(:install) do
        bin.install "orangeshell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/orangeshell/releases/download/v1.7.0/orangeshell_1.7.0_linux_amd64.tar.gz"
      sha256 "7c5cd7a0a8946741efbdc891132aacba3e2afa7599d06564a7a03ebb8fb790c9"
      define_method(:install) do
        bin.install "orangeshell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arafato/orangeshell/releases/download/v1.7.0/orangeshell_1.7.0_linux_arm64.tar.gz"
      sha256 "b48c44099494f28aec38cacfc1f9ba903a257a85fef3a9f72ebdf6303170c783"
      define_method(:install) do
        bin.install "orangeshell"
      end
    end
  end

  test do
    system "#{bin}/orangeshell", "--version"
  end
end
